version: '3.8'
services:
  api:
    image: 'rws'
    restart: always
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres/4pp
    ports:
      - '4000:4000'
    depends_on:
      - postgres
  postgres:
    image: postgres:13.6   
    restart: always
    environment:            
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:                
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'         

volumes:
  postgres:
  